apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-oppslag-inntekt
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  kafka:
    pool: {{ kafka_pool }}
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  observability:
    autoInstrumentation:
      enabled: false
      runtime: java
  env:
    - name: DP_INNTEKT_API_SCOPE
      value: {{dp_inntekt_api_scope}}
  accessPolicy:
    outbound:
      rules:
        - application: dp-inntekt-api