apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-oppslag-inntekt
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: "serviceuser/data/{{ env }}/srvdp-oppslag-innt"
        mountPath: "/var/run/secrets/nais.io/service_user"
